### ISSUE TITLE
Issue Regarding Resources

### ISSUE THREAD

**Issue by prathamesh-borse** [HITK-TECH-Community/HITK_Tech_Community#6]
I just wanted to ask you about what type of resources we can share in this repo to make it more useful for tier 2 and tier 3 colleges.

**Comment by Kajol-Kumari** [comment]
Hey @prathamesh-borse it can be any hackathon, hiring challenge, open source event or domain specific challenge. Think of It like anything that you would have loved to apply for

**Comment by prathamesh-borse** [comment]
@Kajol-Kumari I have shared one resource in the google form could you please check it and do let me know!

**Comment by prathamesh-borse** [comment]
@Kajol-Kumari Can I add that resource to this Repository?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Can I add that resource to this Repository?

Hey! I didn't find it like out-of-box opportunity so I request you not to add it in here. 

Thanks!
